config/routes.rb
Rails.application.routes.draw do
  resources :resources
  root 'talks#index'

  get 'signup', to: 'users#new'

  resources :categories
  resource :session
  resources :users

  resources :talks do
    resources :registrations
    resources :likes
  end
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user # users are 'likers'
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :title, :speaker, presence: true
  validates :topic, length: { minimum: 45 }
  validates :speaker_profile, length: { minimum: 45 }
  validates :capacity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.upcoming
    where('date >= ?', Time.now).order('date')
  end

  def spots_left
    capacity - registrations.count
  end

  def sold_out?
    spots_left.zero?
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @talks = Talk.upcoming
  end

  def show
    @talk = Talk.find(params[:id])
    @likers = @talk.likers
    case
    when current_user && @talk.sold_out?
      flash.now[:notice] = "#{@talk.title} with #{@talk.speaker} is no longer accepting registrations"
      set_upvote
    when current_user
      set_upvote
    end
    @categories = @talk.categories
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update(talk_params)
      redirect_to @talk, notice: "#{@talk.title} with #{@talk.speaker} has been updated!"
    else
      render :edit
    end
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.save
      redirect_to root_path, notice: "#{@talk.title} with #{@talk.speaker} has been added to upcoming talks!"
    else
      render :new
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    title, speaker = @talk.title, @talk.speaker
    @talk.destroy
    redirect_to root_path, notice: "#{title} with #{speaker} has been successfully removed from the site!"
  end

  private

  def set_upvote
    @current_upvote = current_user.likes.find_by(talk_id: @talk.id)
  end

  def talk_params
    params.require(:talk).permit(:title, :topic, :speaker, :speaker_profile, :date, :capacity, :category_ids)
  end
end

app/helpers/talks_helper.rb
module TalksHelper
  def display_registration_for(talk)
    if talk.sold_out?
      content_tag(:p, "Registration is full!", class: 'label label-pill label-danger')
    else
      link_to "Register now!", new_talk_registration_path(talk), class: 'label label-pill label-success'
    end
  end
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
<%= render 'layouts/errors', object: @talk %><br>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :topic %>
    <%= f.text_field :topic %>
  </p>
  <p>
    <%= f.label :speaker %>
    <%= f.text_field :speaker %>
  </p>
  <p>
    <%= f.label :speaker_profile %>
    <%= f.text_area :speaker_profile %>
  </p>
  <p>
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </p>
  <p>
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </p>
  <p>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </p>
  <%= f.submit %>
<% end %>

app/views/talks/edit.html.erb
<div class='container'>
  <h1>Editing <%= @talk.title %><span class="blinking-cursor">|</span></h1>
  <%= render 'form' %>
</div>

app/views/talks/index.html.erb
<div style="background:transparent !important", class="jumbotron jumbotron-fluid centered">
  <div class="container">
    <h1>Candid interviews with those who've been there, coded that, and learned priceless lessons along the way.<span class="blinking-cursor">|</span></h1><br>
    <% unless current_user %>
      <%= link_to 'Claim your free membership today', signup_path, class: 'btn btn-success btn-lg' %>
    <% end %>
  </div>
</div>
<div class='container'>
  <% unless current_user %>
    <div class='existing_member'>
        <h2 class='centered'>Existing memeber? Sign in to register for our <%= pluralize(@talks.count, 'upcoming live talk') %></h2>
      <div class=row>
          <div class="centered">
        <%= render 'sessions/new' %><br>
          </div>
      </div>
    </div>
    <% else %>
    <h2 class='centered'>Welcome back, <%= "#{current_user.first_name}." %> Feel free to register for upcoming talks below:</h2>
  <% end %>
  <br><% @talks.each do |t| %>
    <div class="row">
      <div class="col-md-4 col-md-push-9">
        <img class='speaker-picture', src="http://placehold.it/150x150">
      </div>
      <div class="col-md-7 col-md-pull-3">
        <h3><%=link_to(t.title, t) %>
          <%= display_registration_for(t) %>
        <h5>a conversation with <%= t.speaker %></h5>
        <p class='lead text-muted'><%= truncate(t.topic, :length => 100, separator: ' ') %></p>
        <h4><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= t.date %> (<%= pluralize(t.spots_left, 'available spot')%> left)</h4>
        <% if t.categories.any? %>
        <h4>Topics covered in this talk: </h4>
          <% t.categories.each do |category| %>
            <p><%= category.name %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% if current_user_admin? %>
  <%= link_to('Add a new talk', new_talk_path) %>
<% end %>

app/views/talks/new.html.erb
<div class='container'>
  <h1>Add a new talk<span class="blinking-cursor">|</span></h1>
  <%= render 'form' %>
</div>

app/views/talks/show.html.erb
<div class='container'>
  <h1><%= @talk.title %><span class="blinking-cursor">|</span></h1>
  <span><p class='text-muted lead'><%= @talk.topic %></p><h3><%= display_registration_for(@talk) %></h3></span>
  <img src="http://placehold.it/950x550">
  <h4>About the speaker: </h4>
  <p><%= @talk.speaker_profile %></p>
  <h4>Topics covered in this talk</h4>
  <% if @categories.any? %>
    <% @categories.each do |category| %>
      <p><%= category.name %></p>
    <% end %>
  <% end %>
  <% if current_user %>
    <% if @current_upvote %>
      <h3><%= button_to "Mark this video as unhelpful", talk_like_path(@talk, @current_upvote), class: 'btn btn-danger', method: :delete %></h3>
    <% else %>
      <h3><%= button_to "Mark this video as helpful", talk_likes_path(@talk), class: 'btn btn-success' %></h3>
    <% end %>
  <% end %>
  <p><em>(<%= pluralize(@likers.size, 'member') %> found this video helpful so far)</em></p>

  <% if current_user_admin? %>
    <p class='lead'><%= link_to("View registrations", talk_registrations_path(@talk)) %> <em>(<%= @talk.registrations.count %>)</em></p>
    <%= link_to('Edit this talk', edit_talk_path) %> |
    <%= link_to('Remove this talk', talk_path, method: :delete, data: { confirm: 'Are you sure you want to remove this talk from the site? Note: this is a permanent action. Click \'OK\' to confirm or \'Cancel\' to go back.'}) %> |
  <% end %>
</div>