config/routes.rb
Rails.application.routes.draw do
  resources :resources
  root 'talks#index'

  get 'signup', to: 'users#new'

  resources :categories
  resource :session
  resources :users

  resources :talks do
    resources :registrations
    resources :likes
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_talks, through: :likes, source: :talk # talks are 'liked_talks'

  def self.authenticate(email_address, password)
    user = User.find_by(email_address: email_address)
    user && user.authenticate(password)
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, :last_name, presence: true
  validates :email_address, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, :allow_blank => true

  def gravatar_id
    Digest::MD5::hexdigest(email_address.downcase)
  end

  def admin?
    user_type == 'admin'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @liked_talks = @user.liked_talks
    @registrations = @user.registrations
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome to hacker_talks, #{@user.first_name}! You're all set and ready to go."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Your account has been successfully updated"
    else
      render :edit
    end
  end

  def destroy
    first_name = @user.first_name
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "We're sorry to see you go, #{first_name}! We hope you come back soon."
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email_address, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_path, notice: "Don't worry, we'll open up other people's accounts for viewing soon."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image_for(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.first_name)
  end

  def get_perspective(user)
    if user == current_user
      "you've"
    else
      "#{user.first_name} has"
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'layouts/errors', object: @user %><br>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm your password" %>
    <%= f.password_field :password_confirmation %>
  </p>

  <% unless current_user %>
    <p class='lead'>Already an existing member? <%= link_to "Sign in here", new_session_path %></p>
  <% end %>
  <% if @user.new_record? %>
    <%= f.submit "Get in there, tiger", class: 'btn btn-md btn-success' %>
  <% else %>
    <%= f.submit "Update your account", class: 'btn btn-md btn-success' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <h1>Edit your account<span class="blinking-cursor">|</span></h1>
  <%= profile_image_for(@user) %>
  <p><em>Not digging your Gravatar? </em><%= link_to("Create or update it here", 'http://en.gravatar.com', :target => '_blank')%></p>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Listing all users<span class="blinking-cursor">|</span></h1>

<% @users.each do |u| %>
  <p><%= u.first_name %> <%= u.last_name %> <%= u.email_address %></p>
<% end %>

app/views/users/new.html.erb
<div class='container'>
  <h1>Create your account<span class="blinking-cursor">|</span></h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class='container'>
  <h1><%= "#{@user.first_name} #{@user.last_name}"%><span class="blinking-cursor">|</span></h1>
  <%= profile_image_for(@user) %>
  <p class='lead'>member since <%= @user.created_at %></p>
  <p class='lead'>Membership status: <strong><%= @user.user_type %></strong></p>

  <% if @registrations.any? %>
  <h3>Current and past registrations:</h3>
    <% @registrations.each do |r| %>
      <h4><%= link_to(r.talk.title, r.talk) %> (registered <%= time_ago_in_words(r.created_at) %> ago)</h4>
    <% end %>
  <% end %>
  <h3>Talks <%= get_perspective(@user) %> found helpful:</h3>
  <% @liked_talks.each do |talk| %>
    <h4><%= link_to("#{talk.title}", talk_path(talk))%> by <%= "#{talk.speaker}" %></h4>
  <% end %>
  <% if current_user?(@user) %>
  <%= link_to('Edit your account settings', edit_user_path) %> |
  <%= link_to('Delete your account', user_path, method: :delete, data: { confirm: 'Are you sure you want to delete your account? Note: this is a permanent action that will also delete any registrations associated with your account. Click \'OK\' to confirm or \'Cancel\' to go back.'}) %>
  <% end %>
</div>