config/routes.rb
Rails.application.routes.draw do
  resources :resources
  root 'talks#index'

  get 'signup', to: 'users#new'

  resources :categories
  resource :session
  resources :users

  resources :talks do
    resources :registrations
    resources :likes
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :talk
end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :categorizations, dependent: :destroy
  has_many :talks, through: :categorizations
end

app/models/like.rb
class Like < ActiveRecord::Base
  # join table between users (likers) and talks (liked_talks)
  belongs_to :talk
  belongs_to :user
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :talk
  belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user # users are 'likers'
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :title, :speaker, presence: true
  validates :topic, length: { minimum: 45 }
  validates :speaker_profile, length: { minimum: 45 }
  validates :capacity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.upcoming
    where('date >= ?', Time.now).order('date')
  end

  def spots_left
    capacity - registrations.count
  end

  def sold_out?
    spots_left.zero?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_talks, through: :likes, source: :talk # talks are 'liked_talks'

  def self.authenticate(email_address, password)
    user = User.find_by(email_address: email_address)
    user && user.authenticate(password)
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, :last_name, presence: true
  validates :email_address, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, :allow_blank => true

  def gravatar_id
    Digest::MD5::hexdigest(email_address.downcase)
  end

  def admin?
    user_type == 'admin'
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin
  before_action :set_event, only: [:create, :destroy]

  def create
    @talk.likes.create!(user: current_user)
    redirect_to @talk, notice: "Glad you found #{@talk.title} helpful!"
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy
    redirect_to @talk, notice: "Ah, sorry you didn't find #{@talk.title} very helpful!"
  end

  private

  def set_event
    @talk = Talk.find(params[:talk_id])
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.authenticate(params[:email_address], params[:password])
      session[:user_id] = user.id
      redirect_to session[:last_requested_url] || root_path, notice: "Welcome back, #{user.first_name}!"
      session[:last_requested_url] = nil
    else
      flash.now[:notice] = "Ah snap! Doesn't look like that email/password combo is correct."
      render :new
    end
  end

  def destroy
    @user = current_user
    session[:user_id] = nil
    redirect_to root_path, notice: "You're all signed out, #{@user.first_name}. See you again soon!"
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @talks = Talk.upcoming
  end

  def show
    @talk = Talk.find(params[:id])
    @likers = @talk.likers
    case
    when current_user && @talk.sold_out?
      flash.now[:notice] = "#{@talk.title} with #{@talk.speaker} is no longer accepting registrations"
      set_upvote
    when current_user
      set_upvote
    end
    @categories = @talk.categories
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if @talk.update(talk_params)
      redirect_to @talk, notice: "#{@talk.title} with #{@talk.speaker} has been updated!"
    else
      render :edit
    end
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.save
      redirect_to root_path, notice: "#{@talk.title} with #{@talk.speaker} has been added to upcoming talks!"
    else
      render :new
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    title, speaker = @talk.title, @talk.speaker
    @talk.destroy
    redirect_to root_path, notice: "#{title} with #{speaker} has been successfully removed from the site!"
  end

  private

  def set_upvote
    @current_upvote = current_user.likes.find_by(talk_id: @talk.id)
  end

  def talk_params
    params.require(:talk).permit(:title, :topic, :speaker, :speaker_profile, :date, :capacity, :category_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @liked_talks = @user.liked_talks
    @registrations = @user.registrations
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome to hacker_talks, #{@user.first_name}! You're all set and ready to go."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Your account has been successfully updated"
    else
      render :edit
    end
  end

  def destroy
    first_name = @user.first_name
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "We're sorry to see you go, #{first_name}! We hope you come back soon."
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email_address, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_path, notice: "Don't worry, we'll open up other people's accounts for viewing soon."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
  def display_registration_for(talk)
    if talk.sold_out?
      content_tag(:p, "Registration is full!", class: 'label label-pill label-danger')
    else
      link_to "Register now!", new_talk_registration_path(talk), class: 'label label-pill label-success'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image_for(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.first_name)
  end

  def get_perspective(user)
    if user == current_user
      "you've"
    else
      "#{user.first_name} has"
    end
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <p class='lead'>Ah snap! We found <strong><%= pluralize(object.errors.count, 'error') %></strong> with your submission: </p>
  <% object.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag "hacker_talks-logo.png" %>
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class='container'>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Developer resources", resources_path %></li>
        <% if current_user %>
        <li><div class= 'user_nav_image' ></div><%= link_to profile_image_for(current_user), current_user %></li>
        <li><%= link_to "Sign out", session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerTalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<% if flash[:notice] %>
  <div class='flash centered'><%= flash[:notice]%></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/resources/index.html.erb
<div class='container'>
  <h1>Available resources for programmers<span class="blinking-cursor">|</span></h1>
  <% if @resources.any? %>
    <% @resources.each do |resource| %>
      <p class='lead'><%= link_to(resource.name, resource) %>- <em><%= resource.description %></em></p>
    <% end %>
  <% end %>
</div>